"""change subreddit_subscribers primary key id default behavior

Revision ID: 0ca04725c77c
Revises: 7509be5e0c53
Create Date: 2026-04-09 10:53:43.628145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca04725c77c'
down_revision: Union[str, Sequence[str], None] = '7509be5e0c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        ALTER TABLE subreddit_subscribers
        ALTER COLUMN id SET GENERATED BY DEFAULT
    """)


def downgrade() -> None:
    op.execute("""
        ALTER TABLE subreddit_subscribers
        ALTER COLUMN id SET GENERATED ALWAYS
    """)
