name: Deploy Infra

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - "infrastructure/**"

permissions:
    id-token: write
    contents: read

jobs:
    plan:
        runs-on: ubuntu-latest
        outputs:
            fetcher_image_tag: ${{ steps.fetcher_tag.outputs.fetcher_image_tag }}
            loader_image_tag: ${{ steps.loader_tag.outputs.loader_image_tag }}
        defaults:
            run:
                working-directory: ./infrastructure
        env:
            TF_CLOUD_ORGANIZATION: "dmitkov28"
            TF_WORKSPACE: "reddit-tracker-workspace"
            FETCHER_ECR_REPO: "reddit-tracker-ecr"
            LOADER_ECR_REPO: "reddit-tracker-loader-ecr"

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v6
              with:
                  role-to-assume: arn:aws:iam::029646685128:role/reddit-tracker-gh-actions
                  aws-region: eu-central-1

            - name: Get latest fetcher image tag
              id: fetcher_tag
              run: |
                  IMAGE_TAG=$(aws ecr describe-images \
                  --repository-name ${{ env.FETCHER_ECR_REPO }} \
                  --query 'sort_by(imageDetails, &imagePushedAt)[-1].imageTags[0]' \
                  --output text)
                  echo "fetcher_image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

            
            - name: Get latest loader image tag
              id: loader_tag
              run: |
                  IMAGE_TAG=$(aws ecr describe-images \
                  --repository-name ${{ env.LOADER_ECR_REPO }} \
                  --query 'sort_by(imageDetails, &imagePushedAt)[-1].imageTags[0]' \
                  --output text)
                  echo "loader_image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                  cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

            - name: Create plan
              env:
                  FETCHER_TAG: ${{ steps.fetcher_tag.outputs.fetcher_image_tag }}
                  LOADER_TAG: ${{ steps.loader_tag.outputs.loader_image_tag }}

              run: |
                  terraform init
                  terraform plan --var="fetcher_image_tag=$FETCHER_TAG" --var="loader_image_tag=$LOADER_TAG" -out=tfplan

            - name: Upload Plan
              uses: actions/upload-artifact@v7
              with:
                  name: tfplan
                  path: ./infrastructure/tfplan

    apply:
        needs: plan
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./infrastructure

        environment:
            name: production

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v4
              with:
                  cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

            - name: Download Plan
              uses: actions/download-artifact@v8
              with:
                  name: tfplan
                  path: ./infrastructure

            - name: Terraform Init
              run: terraform init

            - name: Apply Approved Plan
              run: terraform apply tfplan
