name: Deploy

on:
    workflow_dispatch:
    push:
        branches: [main]
        paths:
            - './infrastructure'

permissions:
    id-token: write
    contents: read

jobs:
    terraform:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./infrastructure
        env:
            TF_CLOUD_ORGANIZATION: "dmitkov28"
            TF_WORKSPACE: "reddit-tracker-workspace"
            TF_API_TOKEN: ${{ secrets.TFC_TOKEN }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3

            - name: Create plan
              run: |
                terraform init
                terraform plan --var="image-tag=sha-${{github.sha}}"