name: Deploy Lambda

on:
  workflow_run:
    workflows: ["Build and Push"]
    types:
      - completed
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.calc.outputs.short_sha }}
    steps:
      - id: calc
        run: echo "short_sha=${GITHUB_SHA:0:10}" >> $GITHUB_OUTPUT
  
  build-and-push:
    needs: setup
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ needs.setup.outputs.image_tag }}
    
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::029646685128:role/reddit-tracker-gh-actions
          aws-region: eu-central-1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Update Lambda function code
        env:
          ECR_REGISTRY: 029646685128.dkr.ecr.eu-central-1.amazonaws.com
          ECR_REPOSITORY: reddit-tracker-ecr
          FUNCTION_NAME: reddit-tracker
        run: |
          aws lambda update-function-code \
          --function-name ${{ env.FUNCTION_NAME }} \
          --image-uri ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:sha-${{ github.sha }} \
          > /dev/null