name: Lint Dockerfile

on:
    workflow_dispatch:
    push:
        paths:
            - "./Dockerfile"

jobs:
    hadolint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - uses: hadolint/hadolint-action@v3.1.0
              with:
                  dockerfile: Dockerfile
