name: Test Fetcher
on:
  workflow_dispatch:
  push:
    paths:
      - 'fetcher/src/**'
  pull_request:
    paths:
      - 'fetcher/src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./fetcher
        
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7.6.0
        with:
          version: "latest"
          enable-cache: true

      - run: uv sync
      - run: uv run ruff check
      - run: uvx bandit -r ./src -c pyproject.toml
      - run: uv run pytest
