name: Test
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
  pull_request:
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v7.6.0
        with:
          version: "latest"

      - run: uv sync
      - run: uv run ruff check
      - run: uvx bandit -r ./src -c pyproject.toml
      - run: uv run pytest
